library(RCurl)

## URL de base des résultats sur le site lyon.fr
base.url <- "http://www.elections.lyon.fr/scrutin/bureaux.php?ARRONDISSEMENT=&CANTON=&CIRCONSCRIPTION=&SCRUTIN=33&TOUR=1&TYPE=1&DECOUPAGE=1&BUREAU="

## Data frame comprenant la liste des bureaux (id et nom)
liste.bureaux <- data.frame(rbind(c("0101","MAIRIE DU 1ER ARRONDISSEMENT"),
                       c("0102","MAIRIE DU 1ER ARRONDISSEMENT"),
                       c("0103","ECOLE - VICTOR HUGO"),
                       c("0104","ECOLE - VICTOR HUGO"),
                       c("0105","ECOLE - AVEYRON"),
                       c("0106","ECOLE - AVEYRON"),
                       c("0107","ECOLE - AVEYRON"),
                       c("0108","SERV. ARCHEOLOGIQUE MUNICIPAL"),
                       c("0109","ECOLE TABLES CLAUDIENNES"),
                       c("0110","ECOLE - MICHEL SERVET"),
                       c("0111","MAIRIE - ANNEXE"),
                       c("0112","ECOLE - ROBERT DOISNEAU"),
                       c("0113","ECOLE - ROBERT DOISNEAU"),
                       c("0114","ECOLE - ROBERT DOISNEAU"),
                       c("0115","MAIRIE DU 1ER ARRONDISSEMENT"),
                       c("0116","SERV. ARCHEOLOGIQUE MUNICIPAL"),
                       c("0117","ECOLE TABLES CLAUDIENNES"),
                       c("0201","MAIRIE DU 2 EME"),
                       c("0202","MAIRIE DU 2 EME"),
                       c("0203","ECOLE PRIMAIRE CONDE (GYMNASE)"),
                       c("0204","ECOLE PRIMAIRE CONDE (GYMNASE)"),
                       c("0205","ECOLE MICHELET"),
                       c("0206","ECOLE MICHELET"),
                       c("0207","SALLE FRANCOIS SALA"),
                       c("0208","SALLE FRANCOIS SALA"),
                       c("0209","ECOLE MATERNELLE CONDE"),
                       c("0210","ECOLE MATERNELLE CONDE"),
                       c("0211","ECOLE GILIBERT"),
                       c("0212","ECOLE GILIBERT"),
                       c("0213","ECOLE ALIX"),
                       c("0214","ECOLE ALIX"),
                       c("0215","ECOLE LAMARTINE"),
                       c("0216","ECOLE LAMARTINE"),
                       c("0217","SALLE CORBEILLE"),
                       c("0218","SALLE DE LA CORBEILLE"),
                       c("0219","GYMNASE CHANFRAY"),
                       c("0220","GYMNASE CHANFRAY"),
                       c("0301","MAIRIE DU 3EME"),
                       c("0302","MAIRIE DU 3ÈME"),
                       c("0303","ECOLE ANDRE PHILIP"),
                       c("0304","ECOLE ANDRE PHILIP"),
                       c("0305","ECOLE PAUL PAINLEVE"),
                       c("0306","ECOLE PAUL PAINLEVE"),
                       c("0307","ECOLE PAUL PAINLEVE"),
                       c("0308","ECOLE PAUL PAINLEVE"),
                       c("0309","ECOLE PAUL PAINLEVE"),
                       c("0310","ECOLE SAINT EXUPERY"),
                       c("0311","ECOLE SAINT EXUPERY"),
                       c("0312","ECOLE ETIENNE DOLET"),
                       c("0313","ECOLE ETIENNE DOLET"),
                       c("0314","GYMNASE MAZENOD"),
                       c("0315","GYMNASE MAZENOD"),
                       c("0316","ECOLE LEON JOUHAUX"),
                       c("0317","ECOLE LEON JOUHAUX"),
                       c("0318","ECOLE LEON JOUHAUX"),
                       c("0319","ECOLE ANTOINE CHARIAL"),
                       c("0320","ECOLE ANTOINE CHARIAL"),
                       c("0321","ECOLE GEORGES POMPIDOU"),
                       c("0322","ECOLE LAURENT MOURGUET"),
                       c("0323","ECOLE LAURENT MOURGUET"),
                       c("0324","ECOLE ANTOINE CHARIAL"),
                       c("0325","ECOLE ANTOINE CHARIAL"),
                       c("0326","ECOLE MEYNIS"),
                       c("0327","ECOLE MEYNIS"),
                       c("0328","ECOLE MEYNIS"),
                       c("0329","ECOLE JULES VERNE"),
                       c("0330","ECOLE JULES VERNE"),
                       c("0331","ECOLE ANATOLE FRANCE"),
                       c("0332","ECOLE ANATOLE FRANCE"),
                       c("0333","ECOLE ANATOLE FRANCE"),
                       c("0334","ECOLE ANATOLE FRANCE"),
                       c("0335","ECOLE CONDORCET"),
                       c("0336","ECOLE CONDORCET"),
                       c("0337","ECOLE VIALA"),
                       c("0338","ECOLE VIALA"),
                       c("0339","ECOLE LOUISE"),
                       c("0340","ECOLE LOUISE"),
                       c("0341","ECOLE DOCTEUR REBATEL"),
                       c("0342","ECOLE DOCTEUR REBATEL"),
                       c("0343","ECOLE NOVE JOSSERAND"),
                       c("0344","ECOLE NOVE JOSSERAND"),
                       c("0345","ECOLE NOVE JOSSERAND"),
                       c("0346","ECOLE NOVE JOSSERAND"),
                       c("0347","ECOLE NOVE JOSSERAND"),
                       c("0348","ECOLE MEYNIS"),
                       c("0349","ECOLE AIME CESAIRE"),
                       c("0350","G.S ANTOINE CHARIAL"),
                       c("0351","G.S ANTOINE CHARIAL"),
                       c("0401","MAIRIE DU 4EME ARRDT"),
                       c("0402","MAIRIE DU 4EME ARRDT"),
                       c("0403","ECOLE JOSEPH CORNIER"),
                       c("0404","ECOLE JOSEPH CORNIER"),
                       c("0405","ECOLE JOSEPH CORNIER"),
                       c("0406","ECOLE DES ENTREPOTS"),
                       c("0407","ECOLE DES ENTREPOTS"),
                       c("0408","SALLE MUNICIPALE LA FICELLE"),
                       c("0409","ECOLE DU GROS CAILLOU"),
                       c("0410","ECOLE DU GROS CAILLOU"),
                       c("0411","ECOLE COMMANDANT ARNAUD"),
                       c("0412","ECOLE COMMANDANT ARNAUD"),
                       c("0413","ECOLE COMMANDANT ARNAUD"),
                       c("0414","ECOLE COMMANDANT ARNAUD"),
                       c("0415","ECOLE GEORGES LAPIERRE"),
                       c("0416","ECOLE JEAN DE LA FONTAINE"),
                       c("0417","ECOLE JEAN DE LA FONTAINE"),
                       c("0418","ECOLE JEAN DE LA FONTAINE"),
                       c("0419","GYMNASE RENE BAILLIEU"),
                       c("0420","ECOLE JEAN DE LA FONTAINE"),
                       c("0421","GYMNASE RENE BAILLIEU"),
                       c("0422","SALLE DES FETES DE LA FICELLE"),
                       c("0423","SALLE DES FETES DE LA FICELLE"),
                       c("0424","ECOLE COMMANDANT ARNAUD"),
                       c("0501","MAIRIE DU 5èME"),
                       c("0502","ECOLE FRANCOIS TRUFFAUT"),
                       c("0503","ECOLE FRANCOIS TRUFFAUT"),
                       c("0504","ECOLE FRANCOIS TRUFFAUT"),
                       c("0505","ECOLE MATERNELLE SECRET"),
                       c("0506","ECOLE MATERNELLE SECRET"),
                       c("0507","ECOLE LES GEMEAUX"),
                       c("0508","ECOLE LES GEMEAUX"),
                       c("0509","ECOLE LES GEMEAUX"),
                       c("0510","ECOLE LES GEMEAUX"),
                       c("0511","GYMNASE CHARCOT"),
                       c("0512","GYMNASE CHARCOT"),
                       c("0513","ECOLE FERDINAND BUISSON"),
                       c("0514","ECOLE FERDINAND BUISSON"),
                       c("0515","ECOLE FERDINAND BUISSON"),
                       c("0516","ECOLE FERDINAND BUISSON"),
                       c("0517","ECOLE CHAMPVERT OUEST"),
                       c("0518","ECOLE CHAMPVERT OUEST"),
                       c("0519","ECOLE CHAMPVERT OUEST"),
                       c("0520","ECOLE DIDEROT"),
                       c("0521","ECOLE DIDEROT"),
                       c("0522","ECOLE DIDEROT"),
                       c("0523","ECOLE DIDEROT"),
                       c("0524","ECOLE ALBERT CAMUS"),
                       c("0525","ECOLE ALBERT CAMUS"),
                       c("0526","ECOLE FULCHIRON"),
                       c("0527","ECOLE FULCHIRON"),
                       c("0528","MJC DU VIEUX LYON"),
                       c("0529","MAIRIE ANNEXE"),
                       c("0530","ECOLE GERSON"),
                       c("0531","ECOLE GERSON"),
                       c("0601","MAIRIE DU 6EME"),
                       c("0602","MAIRIE DU 6EME"),
                       c("0603","MAIRIE DU 6EME"),
                       c("0604","GYMNASE VIRICEL"),
                       c("0605","GYMNASE VIRICEL"),
                       c("0606","GYMNASE VIRICEL"),
                       c("0607","ECOLE FERRY"),
                       c("0608","ECOLE FERRY"),
                       c("0609","ECOLE FERRY"),
                       c("0610","ECOLE ANTOINE REMOND"),
                       c("0611","ECOLE ANTOINE REMOND"),
                       c("0612","ECOLE ANTOINE REMOND"),
                       c("0613","ECOLE JEAN JAURES"),
                       c("0614","ECOLE JEAN JAURES"),
                       c("0615","ECOLE CREQUI"),
                       c("0616","ECOLE CREQUI"),
                       c("0617","ECOLE CREQUI"),
                       c("0618","ECOLE CREQUI"),
                       c("0619","GYMNASE MUNICIPAL"),
                       c("0620","GYMNASE MUNICIPAL"),
                       c("0621","GYMNASE MUNICIPAL"),
                       c("0622","GYMNASE MUNICIPAL"),
                       c("0623","GYMNASE MUNICIPAL"),
                       c("0624","GYMNASE MUNICIPAL"),
                       c("0625","GYMNASE MUNICIPAL"),
                       c("0626","ECOLE JEAN ROSTAND (GYMNASE)"),
                       c("0627","ECOLE JEAN ROSTAND (GYMNASE)"),
                       c("0628","ECOLE JEAN ROSTAND (GYMNASE)"),
                       c("0629","ECOLE JEAN ROSTAND"),
                       c("0630","ECOLE JEAN ROSTAND"),
                       c("0631","ECOLE JEAN ROSTAND"),
                       c("0632","LYCEE DU PARC"),
                       c("0633","LYCEE DU PARC"),
                       c("0634","LYCEE DU PARC"),
                       c("0701","MAIRIE DU 7EME ARRT"),
                       c("0702","MAIRIE DU 7EME ARRT"),
                       c("0703","ECOLE BERTHELOT"),
                       c("0704","ECOLE BERTHELOT"),
                       c("0705","ECOLE MATERNELLE GILBERT DRU"),
                       c("0706","ECOLE MATERNELLE GILBERT DRU"),
                       c("0707","ECOLE PASTEUR"),
                       c("0708","ECOLE PASTEUR"),
                       c("0709","ECOLE PRIMAIRE GILBERT DRU"),
                       c("0710","ECOLE PRIMAIRE GILBERT DRU"),
                       c("0711","ECOLE JEAN-MARIE CHAVANT"),
                       c("0712","ECOLE FÉLIX FAURE"),
                       c("0713","ECOLE JEAN MACÉ"),
                       c("0714","ECOLE JEAN MACÉ"),
                       c("0715","ECOLE JEAN MACÉ"),
                       c("0716","ECOLE JEAN MACÉ"),
                       c("0717","ECOLE JEAN-PIERRE VEYET"),
                       c("0718","ECOLE JEAN-PIERRE VEYET"),
                       c("0719","ECOLE JEAN-PIERRE VEYET"),
                       c("0720","ECOLE DOCTEUR CRESTIN"),
                       c("0721","ECOLE DOCTEUR CRESTIN"),
                       c("0722","LYCEE HECTOR GUIMARD"),
                       c("0723","LOCAL MUNICIPAL"),
                       c("0724","LOCAL MUNICIPAL"),
                       c("0725","ECOLE MARCEL PAGNOL"),
                       c("0726","ECOLE CLAUDIUS BERTHELIER"),
                       c("0727","ECOLE MARCEL PAGNOL"),
                       c("0728","ECOLE CLAUDIUS BERTHELIER"),
                       c("0729","ECOLE MARCEL PAGNOL"),
                       c("0730","ECOLE CLAUDIUS BERTHELIER"),
                       c("0731","ECOLE ARISTIDE BRIAND"),
                       c("0732","ECOLE ARISTIDE BRIAND"),
                       c("0733","ECOLE ARISTIDE BRIAND"),
                       c("0734","ECOLE ARISTIDE BRIAND"),
                       c("0735","ECOLE FRANÇOIS RAVIER"),
                       c("0736","ECOLE FRANCOIS RAVIER"),
                       c("0801","MAIRIE DU 8"),
                       c("0802","MAIRIE DU 8"),
                       c("0803","MAIRIE DU 8"),
                       c("0804","GYMNASE COLBERT"),
                       c("0805","GYMNASE COLBERT"),
                       c("0806","GYMNASE COLBERT"),
                       c("0807","ECOLE PAUL EMILE VICTOR"),
                       c("0808","ECOLE  PAUL EMILE VICTOR"),
                       c("0809","ECOLE  LUMIERE"),
                       c("0810","ECOLE LUMIERE"),
                       c("0811","ECOLE  EDOUARD HERRIOT"),
                       c("0812","ECOLE  EDOUARD HERRIOT"),
                       c("0813","ECOLE  EDOUARD HERRIOT"),
                       c("0814","ECOLE  EDOUARD HERRIOT"),
                       c("0815","GYMNASE JEAN MERMOZ"),
                       c("0816","GYMNASE JEAN MERMOZ"),
                       c("0817","ECOLE  PASTEUR  (GYMNASE)"),
                       c("0818","ECOLE  PASTEUR ( GYMNASE)"),
                       c("0819","ECOLE  PASTEUR  (GYMNASE)"),
                       c("0820","ECOLE  JEAN MACE"),
                       c("0821","ECOLE  JEAN MACE"),
                       c("0822","ECOLE  JEAN MACE"),
                       c("0823","ECOLE  JEAN MACE"),
                       c("0824","ECOLE JEAN GIONO"),
                       c("0825","ECOLE  JEAN GIONO"),
                       c("0826","ECOLE  JEAN GIONO"),
                       c("0827","ECOLE  JEAN GIONO"),
                       c("0828","ECOLE  ALAIN FOURNIER"),
                       c("0829","ECOLE ALAIN FOURNIER"),
                       c("0830","ECOLE  CHARLES PEGUY"),
                       c("0831","ECOLE  CHARLES PEGUY"),
                       c("0832","ECOLE CHARLES PEGUY"),
                       c("0833","ECOLE CHARLES PEGUY"),
                       c("0834","ECOLE CHARLES PEGUY"),
                       c("0835","ECOLE COMBE BLANCHE"),
                       c("0836","ECOLE COMBE BLANCHE"),
                       c("0837","ECOLE COMBE BLANCHE"),
                       c("0838","ECOLE PHILIBERT DELORME"),
                       c("0839","ECOLE PHILIBERT DELORME"),
                       c("0840","ECOLE PHILIBERT DELORME"),
                       c("0841","ECOLE PHILIBERT DELORME"),
                       c("0842","ECOLE PHILIBERT DELORME"),
                       c("0843","ECOLE SIMONE SIGNORET"),
                       c("0844","ECOLE EDOUARD HERRIOT"),
                       c("0901","MAIRIE DU 9 EME"),
                       c("0902","MAIRIE DU 9 EME"),
                       c("0903","MAIRIE DU 9 EME"),
                       c("0904","ECOLE DU CHAPEAU ROUGE"),
                       c("0905","ECOLE DU CHAPEAU ROUGE"),
                       c("0906","ECOLE DU CHAPEAU ROUGE"),
                       c("0907","ECOLE JEAN ZAY"),
                       c("0908","ECOLE JEAN ZAY"),
                       c("0909","ECOLE JEAN ZAY"),
                       c("0910","ECOLE HECTOR BERLIOZ"),
                       c("0911","ECOLE  HECTOR BERLIOZ"),
                       c("0912","ECOLE CHEVALIER BAYARD"),
                       c("0913","ECOLE CHEVALIER BAYARD"),
                       c("0914","ECOLE AUDREY HEPBURN"),
                       c("0915","ECOLE AUDREY HEPBURN"),
                       c("0916","ECOLE DE LA GARE D’EAU"),
                       c("0917","ECOLE DE LA GARE D’EAU"),
                       c("0918","ECOLE LES FOUGERES"),
                       c("0919","ECOLE LES ANEMONES"),
                       c("0920","ECOLE LES ANEMONES"),
                       c("0921","ECOLE  LES GERANIUMS"),
                       c("0922","ECOLE LES DAHLIAS"),
                       c("0923","ECOLE LES DAHLIAS"),
                       c("0924","ECOLE ANTONIN LABORDE"),
                       c("0925","ECOLE ANTONIN LABORDE"),
                       c("0926","MAIRIE ST RAMBERT"),
                       c("0927","ECOLE FREDERIC MISTRAL"),
                       c("0928","ECOLE FREDERIC MISTRAL"),
                       c("0929","ECOLE FREDERIC MISTRAL"),
                       c("0930","ECOLE ALPHONSE DAUDET"),
                       c("0931","ECOLE ALPHONSE DAUDET")), stringsAsFactors=FALSE)
names(liste.bureaux) <- c("id","nom")


## Fonction qui extrait les résultats de la page web correspondante à
## l'identifiant d'un bureau

scrape.bureau <- function(id) {
    print(paste0("--- Scraping ",id," ---"))
    ## URL de la page à scraper
    url <- paste0(base.url,id)
    txt = getURL(url)
    ## Scraping
    inscrits <- gsub('.*Inscrits :[ \t]*?</TD>[ \t]*?<TD CLASS="txtbold" ALIGN="right">([0-9]+)[ \t].*', '\\1', txt)
    votants <- gsub('.*en % des inscrits :[ \t]*?</TD>[ \t]*?<TD CLASS="txtbold" ALIGN="left">([0-9.]+)[ \t].*', '\\1', txt)
    blancs <- gsub('.*en % des votants :[ \t]*?</TD>[ \t]*?<TD CLASS="txtbold" ALIGN="left">([0-9.]+)[ \t].*', '\\1', txt)
    joly <- gsub('.*JOLY EVA.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    lepen <- gsub('.*LE PEN MARINE.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    sarkozy <- gsub('.*SARKOZY.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    melenchon <- gsub('.*MÉLENCHON.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    poutou <- gsub('.*POUTOU.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    arthaud <- gsub('.*ARTHAUD.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    cheminade <- gsub('.*CHEMINADE.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    bayrou <- gsub('.*BAYROU.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    dupont.aignan <- gsub('.*DUPONT-AIGNAN.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    hollande <- gsub('.*HOLLANDE.*?<DIV CLASS="arrondiC_txt">([0-9.]+)[ \t].*', '\\1', txt)
    ## Résultats
    result <- c(inscrits=inscrits,
                   abst=100-as.numeric(votants),
                   blancs=blancs,
                   joly=joly,
                   lepen=lepen,
                   sarkozy=sarkozy,
                   melenchon=melenchon,
                   poutou=poutou,
                   arthaud=arthaud,
                   cheminade=cheminade,
                   bayrou=bayrou,
                   dupont.aignan=dupont.aignan,
                   hollande=hollande)
    data.frame(id=as.character(id), lapply(result, as.numeric))
}

## Extraction de l'ensemble des bureaux
votes <- do.call(rbind, lapply(liste.bureaux$id, scrape.bureau))
## Fusion des id et noms de bureaux
votes <- merge(liste.bureaux, votes)

## Check que la somme des pourcentages vaut 100
table(apply(votes[,6:15],1,sum))

## Sauvegarde des données extraites
write.csv(votes, "data/votes.csv")
